#include<stdio.h>
#include<stdlib.h>
typedefstructNode{
intdata;
structNode*prev;
structNode*next;
}Node;
voidinsertAtBeginning(Node**head, int value){
Node*newNode=(Node*)malloc(sizeof(Node));
newNode->data=value;
newNode->prev=NULL;
newNode->next=*head;
if(*head!=NULL)
(*head)->prev=newNode;
*h
}
voidinsertAtEnd(Node**head,intvalue){
Node*newNode=(Node*)malloc(sizeof(Node));
newNode->data=value;
newNode->next=NULL;
if(*head==NULL){
newNode->prev=NULL;
*head=newNode;
return;
}
Node*temp=*head;
while(temp->next!=NULL)
temp=temp->next;
temp->next=newNode;
newNode->prev=temp;
}
voiddisplayForward(Node*head){
printf("Listforward:
");
Node*temp=head;
while(temp!=NULL){
printf("%d<->"
,temp->data);
temp=temp->next;
}
printf("NULL\n");
}
voiddisplayBackward(Node*head){
if(head==NULL){
printf("Listisempty.\n");
return;
}
Node*temp=head;
while(temp->next!=NULL)
temp=temp->next;
printf("Listbackward:
");
while(temp!=NULL){
printf("%d<->"
,temp->data);
temp=temp->prev;
}
printf("NULL\n");
}
voiddeleteNode(Node**head,intvalue){
Node*temp=*head;
while(temp!=NULL&&temp->data!=value){
temp=temp->next;
}
if(temp==NULL){
printf("Value%dnotfoundinthelist.\n"
, value);
return;
}
if(*head==temp)
*head=temp->next;
if(temp->prev !=NULL)
temp->prev->next=temp->next;
if(temp->next!=NULL)
temp->next->prev=temp->prev;
free(temp);
printf("Deleted%dfromthelist.\n"
,value);
}
intmain(){
Node*head=NULL;
insertAtEnd(&head,10);
insertAtBeginning(&head,5);
insertAtEnd(&head,15);
insertAtEnd(&head,20);
displayForward(head);
displayBackward(head);
deleteNode(&head,15);
displayForward(head);
displayBackward(head);
deleteNode(&head,100); 
}