#include<stdio.h>
#include<stdlib.h>
#defineMAX_VERTICES100
typedefstructNode{
intvertex;
structNode*next;
}Node;
typedefstructGraph{
intnumVertices;
Node*adjLists[MAX_VERTICES];
intvisited[MAX_VERTICES];
}Graph
Node*createNode(int v){
Node*newNode=malloc(sizeof(Node));
newNode->vertex=v;
newNode->next=NULL;
returnnewNode;
}
voidinitGraph(Graph*graph,intvertices){
graph->numVertices=vertices;
for(inti=0; i<vertices;i++){
graph->adjLists[i]=NULL;
graph->visited[i]=0;
}
}
voidaddEdge(Graph*graph, int src,intdest){
Node*newNode=createNode(dest);
newNode->next=graph->adjLists[src];
graph->adjLists[src]=newNode;
newNode=createNode(src);
newNode->next=graph->adjLists[dest];
graph->adjLists[dest]=newNode;
}
voidDFS(Graph*graph,intvertex){
graph->visited[vertex]=1;
printf("%d"
,vertex);
Node*temp=graph->adjLists[vertex];
while(temp){
intadjVertex=temp->vertex;
if(!graph->visited[adjVertex]){
DFSgraph,adjVertex);
}
temp=temp->next;
}
}
typedefstructQueue {
intitems[MAX_VERTICES];
intfront;
intrear;
}Queue;
voidinitQueue(Queue*q){
q->front=-1;
q->rear=-1;
}
intisEmpty(Queue*q){
returnq->front==-1;
}
voidenqueue(Queue*q,intvalue){
if(q->rear==MAX_VERTICES- 1){
printf("Queueis full\n");
return;
}
if(q->front==-1)
q->front=0;
q->rear++;
q->items[q->rear]=value;
}
intdequeue(Queue*q){
if(isEmpty(q)){
printf("Queueisempty\n");
return-1;
}
intitem=q->items[q->front];
if(q->front>=q->rear){
q->front=-1;
q->rear=-1;
}else{
q->front++;
}
returnitem;
}
voidBFS(Graph*graph, int startVertex){
Queueq;
initQueue(&q);
graph->visited[startVertex]=1;
enqueue(&q,startVertex);
while(!isEmpty(&q)){
intcurrentVertex=dequeue(&q);
printf("%d"
,currentVertex);
Node*temp=graph->adjLists[currentVertex];
while(temp){
intadjVertex=temp->vertex;
if(!graph->visited[adjVertex]){
graph->visited[adjVertex]=1;
enqueue(&q,adjVertex);
}
temp=temp->next;
}
}
intmain(){
Graphgraph;
intvertices=6;
initGraph(&graph, vertices);
addEdge(&graph,0,1);
addEdge(&graph,0,2);
addEdge(&graph,1,3);
addEdge(&graph,1,4);
addEdge(&graph,2,4);
addEdge(&graph,3,4);
addEdge(&graph,3,5);
addEdge(&graph,4,5);
printf("DFSstartingfromvertex0:\n");
DFS(&graph,0)
for(inti=0; i<vertices;i++){
graph.visited[i]=0;
}
printf("\nBFSstartingfromvertex0:\n");
BFS(&graph,0);
return0;
}