#include<stdio.h>
#defineMAX100
typedefstruct{
intarr[MAX];
intfront;
intrear;
}Queue;
voidinit(Queue*q){
q->front=-1;
q->rear=-1;
}
intisEmpty(Queue*q){
returnq->front==-1;
}
intisFull(Queue *q){
return(q->rear+1)%MAX==q->front;
}
voidenqueue(Queue*q,intvalue){
if(isFull(q)){
printf("QueueOverflow!Cannotenqueue%d\n"
, value);
return;
}
if(isEmpty(q)){
q->front=0;
}
q->rear=(q->rear+1)%MAX;
q->arr[q->rear]=value;
printf("Enqueued%d\n"
, value);
}
intdequeue(Queue*q){
if(isEmpty(q)){
printf("QueueUnderflow!Cannotdequeue\n");
return-1; // Indicate error
}
intvalue=q->arr[q->front];
if(q->front==q->rear){
q->front=-1;
q->rear=-1;
}else{
q->front=(q->front+1) %MAX;
}
returnvalue;
}
intpeek(Queue*q){
if(isEmpty(q)){
printf("Queueisempty\n");
return-1;
}
returnq->arr[q->front];
}
intmain(){
Queueq;
init(&q);
enqueue(&q,10);
enqueue(&q,20);
enqueue(&q,30);
printf("Frontelementis%d\n"
,peek(&q));
printf("Dequeuedelementis%d\n"
,dequeue(&q));
printf("Dequeuedelementis%d\n"
,dequeue(&q));
if(isEmpty(&q)){
printf("Queueisemptynow\n");
}else{
printf("Queueisnotempty\n");
}
return0;
}