#include<stdio.h>
#include<stdlib.h>
typedefstructNode{
intdata;
structNode*next;
}Node;
voidinsertAtBeginning(Node**head, int value){
Node*newNode=(Node*)malloc(sizeof(Node));
newNode->data=value;
newNode->next=*head;
*head=newNode;
}
voidinsertAtEnd(Node**head,intvalue){
Node*newNode=(Node*)malloc(sizeof(Node));
newNode->data=value;
newNode->next=NULL;
if(*head==NULL){
*head=newNode;
return;
}
Node*temp=*head;
while(temp->next!=NULL){
temp=temp->next;
}
temp->next=newNode;
}
voiddisplayList(Node*head){
if(head==NULL){
printf("Listisempty.\n");
return;
}
Node*temp=head;
printf("Linkedlist:
");
while(temp!=NULL){
printf("%d->"
,temp->data);
temp=temp->next;
}
printf("NULL\n");
}
voiddeleteNode(Node**head,intvalue){
Node*temp=*head;
Node*prev=NULL;
if(temp!=NULL&&temp->data==value){
*head=temp->next;
free(temp);
printf("Deleted%dfromthelist.\n"
,value);
return;
}
while(temp!=NULL&&temp->data!=value){
prev=temp;
temp=temp->next;
}
if(temp==NULL){
printf("Value%dnotfoundinthelist.\n"
, value);
return;
}
prev-next=temp->next;
free(temp);
printf("Deleted%dfromthelist.\n"
,value);
}
intmain(){
Node*head=NULL;
insertAtEnd(&head,10);
insertAtBeginning(&head,5);
insertAtEnd(&head,15);
insertAtEnd(&head,20);
displayList(head);
deleteNode(&head,15);
displayList(head);
deleteNode(&head,100); 
return0;
}