#include<stdio.h>
#include<stdlib.h>
typedefstructNode{
intdata;
structNode*left;
structNode*right;
}Node;
Node*createNode(int value){
Node*newNode=(Node*)malloc(sizeof(Node));
newNode->data=value;
newNode->left=NULL;
newNode->right=NULL;
returnnewNode;
}
voidinorder(Node*root){
if(root==NULL)return;
inorder(root->left);
printf("%d"
,root->data);
inorder(root->right);
}
voidpreorder(Node*root){
if(root==NULL)return;
printf("%d"
,root->data);
preorder(root->left);
preorder(root->right
voidpostorder(Node*root){
if(root==NULL)return;
postorder(root->left);
postorder(root->right);
printf("%d"
,root->data);
}
#defineMAX_QUEUE100
typedefstruct{
Node*items[MAX_QUEUE];
intfront,rear;
}Queue;
voidinitQueue(Queue*q){
q->front=0;
q->rear=-1;
}
intisEmpty(Queue*q){
returnq->rear<q->front;
}
voidenqueue(Queue*q,Node*node){
if(q->rear<MAX_QUEUE- 1){
q->items[++q->rear]=node;
}
}
Node*dequeue(Queue*q){
if(!isEmpty(q)){
returnq->items[q->front++];
}
returnNULL;
}
voidlevelOrder(Node*root){
if(root==NULL)return;
Queueq;
initQueue(&q);
enqueue(&q,root);
while(!isEmpty(&q)){
Node*current=dequeue(&q);
printf("%d"
,current->data);
if(current->left!=NULL)enqueue(&q,current->left);
if(current->right!=NULL)enqueue(&q,current->right);
}
}
intmain(){
/*
1
/\
2 3
/ \ \
4 5 6
*/
Node*root=createNode(1);
root->left=createNode(2);
root->right=createNode(3);
root->left->left=createNode(4);
root->left->right=createNode(5);
root->right->right=createNode(6);
printf("Inordertraversal:
");
inorder(root);
printf("\n");
printf("Preordertraversal:
");
preorder(root);
printf("\n");
printf("Postordertraversal:
");
postorder(root);
printf("\n");
printf("Level-ordertraversal:
");
levelOrder(root);
printf("\n");
return0;
}